version: "3.8"
services:
  db:
    image: postgres:16
    container_name: booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  app:
    image: booking_app
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env.prod
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    image: booking_celery
    build:
      context: .
    container_name: celery_worker
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    depends_on:
      - redis

  flower:
    image: booking_flower
    build:
      context: .
    container_name: celery_flower
    command: sh -c "celery --app=app.tasks.celery:celery flower"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: